[package]
name = "soloveyko-ai-video-maker"
version = "4.2.0"
edition = "2024"

[dependencies]
eframe = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
ureq = { version = "2.12.1", features = ["json"] }
rfd = "0.14"
tungstenite = { version = "0.21.0", features = ["rustls-tls-native-roots"] }
sha2 = "0.10"
chrono = "0.4"
msedge-tts = "0.4.0"
rustls = { version = "0.23", features = ["ring"] }
tiktoken = "3"
base64 = "0.22"
zip = "2"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
rodio = { version = "0.19", default-features = false, features = ["wav", "mp3"] }


[package.metadata.bundle]
name = "Soloveyko AI Video Maker"
identifier = "ai.soloveyko.videomaker"
version = "4.2.0"
copyright = "Copyright © 2026 Soloveyko.ai. All rights reserved."
short_description = "Soloveyko.AI-Video.Maker Application"
long_description = "An amazing cross-platform desktop video maker using Rust and egui."
