[package]
name = "soloveyko-video-maker"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
ureq = { version = "2.12.1", features = ["json"] }
rfd = "0.14"
tungstenite = { version = "0.21.0", features = ["rustls-tls-native-roots"] }
sha2 = "0.10"
chrono = "0.4"
msedge-tts = "0.4.0"
rustls = { version = "0.23", features = ["ring"] }


[package.metadata.bundle]
name = "Soloveyko Video Maker"
identifier = "ai.soloveyko.videomaker"
version = "0.1.0"
copyright = "Copyright © 2026 Soloveyko.ai. All rights reserved."
short_description = "Soloveyko.ai Video Maker Application"
long_description = "An amazing cross-platform desktop video maker using Rust and egui."
