package utils

import (
	"fmt"
	"regexp"
	"strings"
)

// SrtToAss converts SRT subtitle content to ASS format using provided settings
func SrtToAss(srtContent string, settings *PipelineSettings) (string, error) {
	// Simple SRT parsing regex
	re := regexp.MustCompile(`(?m)^(\d+)\s*\r?\n(\d{2}:\d{2}:\d{2},\d{3}) --> (\d{2}:\d{2}:\d{2},\d{3})\r?\n([\s\S]*?)(?:\r?\n\r?\n|$)`)
	matches := re.FindAllStringSubmatch(srtContent, -1)

	if len(matches) == 0 {
		return "", fmt.Errorf("no valid SRT blocks found")
	}

	// Use defaults if settings are nil or empty
	fontName := "Arial"
	fontSize := 24
	primaryColor := "&H00FFFFFF" // White
	if settings != nil {
		if settings.SubtitleFont != "" {
			fontName = settings.SubtitleFont
		}
		if settings.SubtitleSize > 0 {
			fontSize = settings.SubtitleSize
		}
		if settings.SubtitleColor != "" {
			primaryColor = hexToAssColor(settings.SubtitleColor)
		}
	}

	var sb strings.Builder

	// Write ASS Header
	sb.WriteString("[Script Info]\n")
	sb.WriteString("Title: Generated by Soloveyko AI\n")
	sb.WriteString("ScriptType: v4.00+\n")
	sb.WriteString("WrapStyle: 0\n")
	sb.WriteString("ScaledBorderAndShadow: yes\n")
	sb.WriteString("YCbCr Matrix: TV.601\n")
	sb.WriteString("PlayResX: 1920\n")
	sb.WriteString("PlayResY: 1080\n")
	sb.WriteString("\n")

	// Write V4+ Styles
	sb.WriteString("[V4+ Styles]\n")
	sb.WriteString("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
	// Styles: PrimaryColour is &HAABBGGRR
	sb.WriteString(fmt.Sprintf("Style: Default,%s,%d,%s,&H000000FF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,3,1,2,60,60,80,1\n", fontName, fontSize, primaryColor))
	sb.WriteString("\n")

	// Write Events
	sb.WriteString("[Events]\n")
	sb.WriteString("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

	fadeTag := ""
	if settings != nil && settings.SubtitleFadeEnabled {
		// \fad(in, out) - values in ms
		fadeTag = fmt.Sprintf("{\\fad(%d,%d)}", settings.SubtitleFadeIn, settings.SubtitleFadeOut)
	}

	for _, match := range matches {
		start := formatSrtTimeToAss(match[2])
		end := formatSrtTimeToAss(match[3])
		text := cleanSrtText(match[4])

		sb.WriteString(fmt.Sprintf("Dialogue: 0,%s,%s,Default,,0,0,0,,%s%s\n", start, end, fadeTag, text))
	}

	return sb.String(), nil
}

// hexToAssColor converts #RRGGBB or #RRGGBBAA to &HAABBGGRR
func hexToAssColor(hex string) string {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) == 6 {
		// RRGGBB -> &H00BBGGRR
		r := hex[0:2]
		g := hex[2:4]
		b := hex[4:6]
		return fmt.Sprintf("&H00%s%s%s", b, g, r)
	} else if len(hex) == 8 {
		// RRGGBBAA -> &HAABBGGRR
		// Note: ASS alpha is 00 for opaque, FF for transparent. CSS is the opposite.
		r := hex[0:2]
		g := hex[2:4]
		b := hex[4:6]
		a := hex[6:8]
		// Convert CSS alpha to ASS alpha (roughly)
		// We'll just simplify and keep it opaque or use provided alpha if needed,
		// but usually users expect hex to be opaque in these cases.
		return fmt.Sprintf("&H%s%s%s%s", a, b, g, r)
	}
	return "&H00FFFFFF"
}

// formatSrtTimeToAss converts 00:00:01,000 to 0:00:01.00
func formatSrtTimeToAss(srtTime string) string {
	// srtTime is HH:MM:SS,mmm
	// assTime is H:MM:SS.cc
	parts := strings.Split(srtTime, ",")
	if len(parts) != 2 {
		return "0:00:00.00"
	}

	hms := parts[0]
	ms := parts[1]

	// Convert ms (3 digits) to centiseconds (2 digits)
	cs := ms[:2]

	// Remove leading zero from hours if present
	if len(hms) > 0 && hms[0] == '0' {
		hms = hms[1:]
	}

	return fmt.Sprintf("%s.%s", hms, cs)
}

func cleanSrtText(text string) string {
	// Remove HTML tags often found in SRT (like <i>)
	reTags := regexp.MustCompile(`<[^>]*>`)
	text = reTags.ReplaceAllString(text, "")

	// Replace \n with \N for ASS
	text = strings.ReplaceAll(text, "\r\n", "\\N")
	text = strings.ReplaceAll(text, "\n", "\\N")

	// Trim whitespace
	text = strings.TrimSpace(text)

	// Final clean up of dual \N or multiple spaces
	for strings.Contains(text, "  ") {
		text = strings.ReplaceAll(text, "  ", " ")
	}

	return text
}
