/// Повертає переклад для англійської мови.
pub fn translate_en(key: &str) -> &'static str {
    match key {
        "app_title" => "Soloveyko.ai Video Maker",
        "tab_main" => "Main",
        "tab_settings" => "Settings",
        "pipeline_settings" => "Pipeline Settings",
        "templates" => "Templates",
        "storage" => "Storage Path",
        "api" => "API",
        "translation" => "Translation",
        "voiceover" => "Voiceover",
        "video" => "Video Sequence",
        "editing" => "Editing",
        "editor_hint" => "Enter or paste the text of your future video script here...",
        "settings_general" => "General",
        "settings_general_title" => "General Settings",
        "settings_theme" => "Theme",
        "settings_theme_desc" => "Select GUI color scheme:",
        "settings_theme_light" => "Light Theme",
        "settings_theme_dark" => "Dark Theme",
        "settings_theme_amoled" => "AMOLED Black Theme",
        "settings_accent" => "Accent Color",
        "settings_accent_desc" => "Select color for highlights, active elements, and navigation:",
        "settings_accent_quick" => "Quick select:",
        "settings_accent_custom" => "Custom color from palette:",
        "settings_data" => "Data Management",
        "settings_data_desc" => "Open local folder containing settings.json:",
        "settings_open_folder" => "Open User Folder",
        "settings_lang" => "Interface Language",
        "settings_lang_desc" => "Select application display language:",
        "settings_lang_uk" => "Ukrainian",
        "settings_lang_en" => "English",
        "settings_lang_ru" => "Russian",
        "color_blue" => "Blue",
        "color_green" => "Green",
        "color_red" => "Red",
        "color_orange" => "Orange",
        "color_purple" => "Purple",
        _ => "",
    }
}
