/// Повертає переклад для англійської мови.
pub fn translate_en(key: &str) -> &'static str {
    match key {
        "app_title" => "Soloveyko.AI-Video.Maker",
        "tab_main" => "Main",
        "tab_settings" => "Settings",
        "templates" => "Templates",
        "storage" => "Storage Path",
        "api" => "API",
        "control" => "Control",
        "control_translation" => "Translation Control",
        "control_auto_open" => "Show control window automatically",
        "control_media" => "Image Control",
        "control_montage" => "Montage Control",
        "montage_editor_title" => "Montage Editor",
        "montage_editor_maximize" => "Maximize",
        "montage_editor_restore" => "Restore",
        "montage_editor_open_btn" => "✂ Montage Editor",
        "montage_editor_play" => "Play",
        "montage_editor_pause" => "Pause",
        "montage_editor_stop" => "Stop",
        "montage_preview_settings" => "Preview:",
        "montage_preview_quality_performance" => "Fast",
        "montage_preview_quality_balanced" => "Balanced",
        "montage_preview_quality_high" => "Quality",
        "montage_preview_quality_ultra" => "Ultra",
        "montage_editor_clips" => "clips",
        "montage_editor_track_video" => "Video",
        "montage_editor_track_audio" => "Audio",
        "montage_editor_info_path" => "Path:",
        "montage_editor_no_data" => "⚠ timeline.json not found. Run the task first.",
        "agent_chat_title" => "Chat with Agent",
        "agent_chat_send_btn" => "Send",
        "agent_chat_rebuild_btn" => "Rebuild Timeline",
        "agent_awaiting_hint" => {
            "Pipeline paused. Chat with the agent and press 'Resume' when segments.json is ready."
        }
        "agent_resume_pipeline_btn" => "▶ Resume Pipeline",
        "agent_chat_confirm_btn" => "✓ Confirm",
        "agent_chat_confirm_tooltip" => "Confirm — pipeline will continue",
        "agent_chat_input_hint" => "Message to agent...",
        "agent_chat_loading" => "Agent is responding...",
        "agent_chat_open_btn" => "Chat with Agent",
        "agent_chat_error" => "Error:",
        "queue_status_awaiting_montage" => "Awaiting Montage Control",
        "queue_status_awaiting_agent" => "Awaiting Agent Confirmation",
        "montage_editor_continue" => "▶ Continue Render",
        "montage_render_ffmpeg" => "🎬 FFmpeg",
        "montage_render_capcut" => "✂ CapCut",
        "montage_editor_media_pool" => "Media Pool",
        "montage_editor_add_media" => "+ Add",
        "montage_editor_drop_here" => "⬇ Drop files here",
        "montage_editor_animate_all" => "Animate all images",
        "montage_editor_animate_selected" => "Animate selected",
        "montage_editor_animate" => "Animate",
        "montage_editor_regen_same" => "Regenerate",
        "montage_editor_regen_custom" => "Regenerate (custom)",
        "montage_editor_replace_stock" => "🔄 Replace stock media",
        "montage_editor_inspector" => "Inspector",
        "montage_editor_no_selection" => "Select a clip on the timeline",
        "montage_editor_clip_start" => "Start (s):",
        "montage_editor_clip_dur" => "Duration (s):",
        "montage_editor_clip_track" => "Track:",
        "montage_editor_delete_clip" => "🗑 Delete Clip",
        "montage_editor_unlink_audio" => "🔓 Unlink audio",
        "montage_editor_link_audio" => "🔗 Link audio",
        "montage_editor_delete_audio_clip" => "🗑 Delete audio",
        "montage_editor_add_video_track" => "+ Video",
        "montage_editor_add_audio_track" => "+ Audio",
        "montage_editor_overlap_transition" => "Transition",
        "montage_editor_tracks_count" => "tracks",
        "montage_editor_transform" => "Transform",
        "montage_editor_clip_scale" => "Scale:",
        "montage_editor_clip_pos_x" => "Pos X:",
        "montage_editor_clip_pos_y" => "Pos Y:",
        "montage_editor_reset_transform" => "↺ Reset",
        "montage_editor_clip_opacity" => "Opacity:",
        "montage_editor_effects" => "Effects",
        "montage_editor_clip_zoom" => "Zoom",
        "montage_editor_clip_shake" => "Shake",
        "montage_editor_split_tool" => "✂ Split",
        "montage_editor_split_at_playhead" => "Split at playhead",
        "montage_editor_undo" => "↩ Undo",
        "montage_editor_redo" => "↪ Redo",
        "translation" => "Translation",
        "voiceover" => "Voiceover",
        "video" => "Video Sequence",
        "video_upscale_label" => "Upscale",
        "video_upscale_resolution_label" => "Target video resolution:",
        "video_upscale_quality_label" => "Re-encoding quality (FFmpeg preset):",
        "video_upscale_quality_fast" => "Fast",
        "video_upscale_quality_balanced" => "Balanced",
        "video_upscale_quality_max" => "Max",
        "video_prompts" => "Prompts",

        "video_media" => "Media",
        "subtitles" => "Subtitles",
        "editing" => "Editing",
        "editor_hint" => "Enter or paste the text of your future video script here...",
        "settings_general" => "General",
        "settings_general_title" => "General Settings",
        "settings_theme" => "Theme",
        "settings_theme_desc" => "Select GUI color scheme:",
        "settings_theme_light" => "Light Theme",
        "settings_theme_dark" => "Dark Theme",
        "settings_theme_amoled" => "AMOLED Black Theme",
        "settings_accent" => "Accent Color",
        "settings_accent_desc" => "Select color for highlights, active elements, and navigation:",
        "settings_accent_quick" => "Quick select:",
        "settings_accent_custom" => "Custom color from palette:",
        "settings_data" => "Data Management",
        "settings_data_desc" => "Open local folder containing settings.json:",
        "settings_open_folder" => "Open User Folder",
        "settings_show_welcome" => "Show welcome window on startup",
        "settings_lang" => "Interface Language",
        "settings_lang_desc" => "Select application display language:",
        "settings_lang_uk" => "Ukrainian",
        "settings_lang_en" => "English",
        "settings_lang_ru" => "Russian",
        "color_blue" => "Blue",
        "color_green" => "Green",
        "color_red" => "Red",
        "color_orange" => "Orange",
        "color_purple" => "Purple",
        "api_key" => "API Key",
        "api_provider" => "Provider",
        "api_model" => "Default Model",
        "api_voice" => "Default Voice",
        "api_style" => "Default Style",
        "api_status" => "Status",
        "api_status_connected" => "Connected",
        "api_status_not_configured" => "Not Configured",
        "api_check_connection" => "Check Connection",
        "api_check_btn" => "Test",
        "api_status_empty" => "⚠ Key is empty",
        "api_status_success" => "✔ Key validated successfully",
        "api_status_invalid" => "❌ Invalid format (must start with sk-or-)",
        "api_stability" => "Voice Stability",
        "api_similarity" => "Similarity",
        "api_resolution" => "Resolution",
        "api_creativity" => "Creativity (Temperature)",
        "api_max_tokens" => "Max Tokens",
        "template_name_hint" => "Template name...",
        "template_save_btn" => "Save",
        "template_status_empty" => "⚠ Template name cannot be empty",
        "template_status_saved" => "Template saved successfully",
        "templates_empty" => "No saved templates",
        "template_loaded" => "Template loaded",
        "template_deleted" => "Template deleted",
        "voicebot_key_hint" => "Enter X-API-Key...",
        "voicebot_status_checking" => "⏳ Checking...",
        "voicebot_key_required" => "⚠ Enter Voice Bot key in the API section",
        "voiceover_provider_label" => "Voiceover Provider",
        "voiceover_templates_loading" => "Loading templates...",
        "voiceover_templates_retry" => "🔄 Retry",
        "voiceover_template_hint" => "Select voice template...",
        "prompt_expand_hint" => "Open in a separate window",
        "translation_prompt_label" => "Translation Prompt",
        "translation_prompt_hint" => "Enter instructions for the translation model...",
        "translation_insert_placeholder" => "{{text}}",
        "translation_placeholder_hint" => {
            "{{text}} - place where the translation text will be inserted."
        }
        "translation_model_label" => "Translation Model",
        "model_label" => "Model",
        "translation_model_hint" => "Select model...",
        "translation_models_loading" => "Loading models...",
        "translation_models_retry" => "🔄 Retry",
        "translation_model_search" => "🔍 Search model...",
        "translation_temperature_label" => "Temperature",
        "translation_service_label" => "Translation Service",
        "translation_service_openrouter" => "OpenRouter",
        "translation_service_claude_code" => "Claude Code",
        "translation_service_gemini_cli" => "Gemini CLI",
        "translation_service_codex_cli" => "Codex CLI",
        "translation_service_agy_cli" => "AGY CLI",
        "translation_service_pi_cli" => "Pi CLI",
        "tab_logs" => "Log",
        "logs_clear" => "🗑 Clear log",
        "logs_copy" => "📋 Copy",
        "logs_copy_line_tooltip" => "Copy this line to clipboard",
        "logs_click_to_copy" => "Click to copy this line",
        "logs_autoscroll" => "Auto-scroll",
        "logs_copied_toast" => "📋 Log text copied to clipboard!",
        "job_logs_copy_all" => "📋 Copy entire job log",
        "logs_empty" => "Log is empty. Run a translation job to see execution logs.",
        "settings_openrouter_threads" => "Max OpenRouter threads",
        "settings_claude_threads" => "Max Claude Code threads",
        "settings_gemini_threads" => "Max Gemini CLI threads",
        "settings_codex_threads" => "Max Codex CLI threads",
        "settings_agy_threads" => "Max AGY CLI threads",
        "settings_pi_threads" => "Max Pi CLI threads",
        "settings_googler_image_threads" => "Max Googler image threads",
        "settings_googler_video_threads" => "Max Googler video threads",
        "googler_key_hint" => "Enter Googler API key...",
        "assemblyai_key_hint" => "Enter AssemblyAI API key...",
        "pexels_key_hint" => "Enter Pexels API key...",
        "pexels_status_checking" => "⏳ Checking...",
        "pexels_service_note" => {
            "Keywords are generated automatically. You pick media manually in the picker."
        }
        "pixabay_key_hint" => "Enter Pixabay API key...",
        "pixabay_service_note" => {
            "Keywords are generated automatically. You pick media manually in the picker."
        }
        "googler_status_checking" => "⏳ Checking...",
        "text_split_mode_label" => "Text split mode",
        "text_split_paragraphs" => "Paragraphs",
        "text_split_paragraphs_hint" => {
            "Text is split into paragraphs. Each paragraph is inserted into the prompt in place of {{text}}."
        }
        "text_split_sentences" => "Sentences",
        "text_split_sentences_hint" => {
            "Text is split into sentences by . ! ? — each sentence becomes a separate frame."
        }
        "text_split_char_limit" => "Char limit",
        "text_split_char_limit_hint" => {
            "Text is split into chunks up to the specified character count. Breaks occur at punctuation or spaces to avoid cutting words."
        }
        "text_split_full" => "Full text",
        "text_split_full_hint" => {
            "The entire text is passed as one block. {{text}} is replaced with the full content."
        }
        "video_service_label" => "Video Service",
        "video_media_type_label" => "Media Type",
        "video_media_type_image" => "Images",
        "video_media_type_video" => "Video",
        "video_prompt_label" => "Video Prompt",
        "video_prompt_hint" => "Enter instructions for image generation...",
        "video_agent_mode_label" => "Agent submode",
        "video_agent_mode_full" => "Full Agent",
        "video_agent_mode_full_hint" => {
            "The agent builds the whole segments.json, including timings and text."
        }
        "video_agent_mode_prompt_only" => "Prompt Only",
        "video_agent_mode_prompt_only_hint" => {
            "The app builds segments.json from split settings first, then the agent edits only the text field."
        }
        "video_agent_prompt_label" => "Agent instruction (segments.json)",
        "video_style_label" => "Specify style",
        "video_style_prompt_label" => "Style prompt for media generation",
        "video_style_prompt_hint" => {
            "{{text}} — text from the 'text' field in segments.json will be inserted here"
        }
        "video_style_insert_placeholder" => "{{text}}",
        "video_insert_placeholder" => "{{text}}",
        "video_insert_context_placeholder" => "{{context}}",
        "video_placeholder_hint_basic" => "{{text}} - segment text.",
        "video_placeholder_hint" => {
            "{{text}} - segment text, {{context}} - extra context for API mode."
        }
        "video_context_label" => "Context for API prompt",
        "video_context_around" => "Around segment",
        "video_context_around_hint" => {
            "{{context}} receives the segment plus nearby text before and after it. The character count is a target; boundaries snap to sentence endings."
        }
        "video_context_full" => "Full text",
        "video_context_full_hint" => "{{context}} receives the full story text.",
        "video_context_chars_label" => "Target chars around:",
        "video_context_hint" => {
            "If {{context}} is missing in the prompt, context will be appended automatically."
        }
        "balance_window_title" => "Balances",
        "threads_window_title" => "Threads",
        "balance_refresh" => "Refresh",
        "balance_refresh_all" => "Refresh all",
        "balance_not_loaded" => "Not loaded",
        "balance_no_key" => "Key not configured",
        "balance_img_per_hour" => "Images / hr",
        "balance_video_per_hour" => "Video / hr",
        "balance_img_threads" => "Image threads",
        "balance_video_threads" => "Video threads",
        "storage_path_label" => "Output Folder",
        "storage_path_hint" => "Select or type a folder path...",
        "storage_browse_btn" => "Browse",
        "storage_path_macos" => "macOS",
        "storage_path_windows" => "Windows",
        "storage_path_active" => "(active)",
        "queue_add_btn" => "Add to Queue",
        "queue_panel_title" => "Queue",
        "queue_collapse_tooltip" => "Collapse panel",
        "queue_expand_tooltip" => "Expand panel",
        "queue_fullscreen_tooltip" => "Expand to full screen",
        "queue_fullscreen_exit_tooltip" => "Exit full screen",
        "queue_run_btn" => "▶ Run",
        "queue_clear_btn" => "🗑 Clear",
        "queue_clear_disabled_hint" => "Cannot clear: there are active tasks",
        "queue_status_pending" => "Pending",
        "queue_status_running" => "Running...",
        "queue_status_awaiting_control" => "Awaiting Control",
        "queue_status_awaiting_media" => "Awaiting Media Control",
        "stock_picker_close" => "Close",
        "stock_search_retrigger" => "Re-search with new prompt",
        "stock_no_results" => "No search results",
        "stock_trim_label" => "Video trim",
        "stock_trim_start" => "From:",
        "stock_trim_end" => "To:",
        "stock_trim_confirm" => "Confirm",
        "stock_trim_cancel" => "Cancel",
        "stock_key_missing_warning" => {
            "⚠️ Missing API key for the selected stock service. Add it in the API settings."
        }
        "stock_services_btn" => "🌐 Services",
        "stock_search_in" => "Search in:",
        "queue_status_done" => "Done",
        "queue_status_failed" => "Failed",
        "control_window_title" => "Translation Control",
        "control_window_text" => {
            "Review and edit the translated text before continuing the pipeline:"
        }
        "control_window_continue_btn" => "Confirm & Continue",
        "control_window_cost" => "Cost:",
        "control_regen_btn" => "🔄 Regenerate",
        "control_regen_extended_btn" => "⚙ Extended",
        "control_regen_extended_title" => "Extended Regeneration",
        "control_regen_loading" => "Regenerating...",
        "control_regen_settings_note" => {
            "These settings are one-time and do not modify pipeline settings."
        }
        "control_regen_run_btn" => "🔄 Regenerate with these settings",
        "control_regen_error" => "❌ Regeneration error:",
        "queue_error_no_text" => "⚠ Script text is empty",
        "queue_error_no_save_path" => "⚠ Specify an output folder",
        "queue_error_no_model" => "⚠ Select a translation model",
        "queue_error_no_key" => "⚠ Enter the OpenRouter key in the API section",
        "queue_error_no_voicebot_key" => "⚠ Enter the VoiceBot key in the API section",
        "voiceover_text_source_original" => "Original",
        "queue_error_no_name" => "⚠ Task name cannot be empty",
        "queue_error_create_dir" => "⚠ Failed to create task folder",
        "job_name_dialog_title" => "Task Name",
        "job_name_hint" => "Leave empty for auto name...",
        "job_name_auto" => "Task",
        "job_name_confirm_btn" => "Add",
        "job_name_cancel_btn" => "Cancel",
        "stage_retry_tooltip" => "Retry this stage and all following",
        "job_retry_tooltip" => "Retry the entire job from scratch",
        "job_open_folder_tooltip" => "Open job folder",
        "job_logs_title" => "Job Logs",
        "job_logs_empty" => "No logs found for this job.",
        "welcome_title" => "Welcome!",
        "welcome_desc" => "Let's check whether the required CLI tools are installed.",

        "welcome_gemini_desc" => {
            "Google Gemini CLI — use your Gemini subscription for prompt generation"
        }
        "welcome_claude_desc" => "Claude Code CLI — use your Claude subscription for text tasks",
        "welcome_codex_desc" => "Codex CLI — use local models and agents for workflow automation",
        "welcome_dont_show" => "Don't show on next launch",
        "welcome_close_btn" => "Got it",
        "welcome_checking" => "checking...",
        "welcome_not_installed" => "not installed",
        "welcome_recheck_btn" => "↺ Recheck",
        "welcome_ffmpeg_desc" => "FFmpeg — audio/video processing, WAV format conversion",
        "welcome_whisper_desc" => "Whisper — speech recognition for subtitle generation",
        "welcome_whisperx_desc" => {
            "WhisperX — enhanced subtitle engine with more precise synchronization"
        }
        "welcome_whisper_amd_desc" => {
            "Whisper AMD — Whisper with AMD GPU support (ROCm). Optional replacement for AMD GPU owners."
        }
        "welcome_whisper_amd_optional" => "optional",
        "welcome_whisper_amd_install_btn" => "Install",
        "subtitles_whisper_amd_not_installed" => {
            "⚠ Whisper AMD is not installed. Click 'Install' in the Welcome window."
        }
        "balance_edge_tts_status" => "Free (No limits)",
        "balance_voicebot_limit" => "Threads limit: 5 (fixed)",
        "balance_assemblyai_limit" => "Threads limit: 5 (fixed)",
        "balance_active_threads" => "Active threads:",
        "settings_edge_tts_threads" => "Edge TTS Parallel Threads:",
        "settings_ffmpeg_threads" => "FFmpeg Parallel Processes:",
        "edge_tts_voices_loading" => "Loading Edge TTS voices...",
        "edge_tts_voice_label" => "Voiceover Voice:",
        "edge_tts_show_all" => "Show all languages",
        "edge_tts_rate_label" => "Rate:",
        "edge_tts_pitch_label" => "Pitch:",
        "edge_tts_volume_label" => "Volume:",
        "stats_chars" => "Characters:",
        "stats_words" => "Words:",
        "stats_paragraphs" => "Paragraphs:",
        "stats_tokens" => "Tokens:",
        "stats_fragments_paragraphs" => "Par.:",
        "stats_fragments_sentences" => "Sen.:",
        "stats_fragments_chars" => "Limit:",
        "stats_chars_short" => "chars",
        "stats_tokens_short" => "tokens",
        "voiceover_convert_to_wav" => "Convert to WAV",
        "queue_waiting_translation" => "awaiting translation",
        "time_hours_short" => "h ",
        "time_mins_short" => "m ",
        "time_secs_short" => "s",
        "video_priorities_btn" => "⚙ Priorities",
        "video_priorities_title" => "Generation Priorities (Googler)",
        "video_priorities_image" => "Images",
        "video_priorities_video" => "Video",
        "video_priorities_retry_hint" => "3 attempts per provider, 5s delay, then next",
        "subtitles_service_label" => "Subtitle Service",
        "subtitles_whisper_model_label" => "Whisper Model",
        "subtitles_whisper_lang_label" => "Recognition Language",
        "subtitles_whisper_lang_auto" => "Auto (detect)",
        "subtitles_no_audio" => {
            "⚠ Audio file not found. Enable the voiceover stage or ensure voice.mp3/voice.wav exists."
        }
        "subtitles_stage_log_start" => "Starting subtitle generation via Whisper...",
        "subtitles_stage_log_done" => "Subtitles saved: subtitle.srt",
        "subtitles_model_downloaded" => "✓ Model downloaded",
        "subtitles_model_download_btn" => "⬇ Download",
        "subtitles_model_retry" => "↺ Retry",
        "subtitles_model_failed" => "❌ Error:",
        "subtitles_whisper_max_len_label" => "Max chars per segment",
        "subtitles_style_label" => "Subtitle Style",
        "subtitles_font_size_label" => "Font Size",
        "subtitles_font_label" => "Font",
        "subtitles_color_label" => "Text Color",
        "subtitles_outline_color_label" => "Outline Color",
        "subtitles_margin_v_label" => "Bottom Margin",
        "subtitles_karaoke_label" => "Karaoke Effect (highlight current word)",
        "subtitles_karaoke_style_label" => "Animation Style",
        "subtitles_karaoke_fill" => "Fill (kf)",
        "subtitles_karaoke_switch" => "Switch (k)",
        "subtitles_karaoke_follow" => "Current only (follow)",
        "subtitles_karaoke_highlight_color_label" => "Active word color",
        "subtitles_karaoke_scale_label" => "Active word scale",
        "subtitles_karaoke_bold_label" => "Bold text",
        "capcut_toggle_label" => "Generate CapCut project",
        "capcut_draft_path_label" => "CapCut Drafts Folder",
        "capcut_draft_path_hint" => "Path to CapCut drafts folder...",
        "montage_service_label" => "Assembly service",
        "montage_fps_label" => "FPS",
        "montage_preset_label" => "Encoding preset",
        "montage_bitrate_label" => "Bitrate",
        "montage_transition_label" => "Transition",
        "montage_transition_duration_label" => "Transition duration",
        "montage_transition_none" => "No transition",
        "montage_transition_random" => "Random",
        "montage_image_zoom_label" => "Zoom effect",
        "montage_image_zoom_mode_label" => "Zoom mode",
        "montage_image_zoom_mode_alternate" => "Alternating",
        "montage_image_zoom_mode_oscillate" => "Back & forth",
        "montage_image_zoom_scale_label" => "Zoom scale",
        "montage_image_zoom_intensity_label" => "Zoom intensity",
        "montage_image_shake_label" => "Camera shake",
        "montage_image_shake_intensity_label" => "Shake intensity",
        "montage_image_effects_note" => "Effects apply to images only",
        "overlay_triggers_label" => "Media triggers",
        "overlay_triggers_phrase" => "Key phrase",
        "overlay_triggers_phrase_hint" => "e.g. hello everyone",
        "overlay_triggers_path" => "Media file",
        "overlay_triggers_path_hint" => "path to file",
        "overlay_triggers_select_file" => "Browse...",
        "overlay_triggers_add" => "+ Add trigger",
        "overlay_triggers_duplicate" => "Duplicate trigger",
        "video_llm_service_label" => "LLM service for prompts",
        "video_llm_mode_label" => "Operation Mode",
        "video_llm_mode_api" => "API",
        "video_llm_mode_agent" => "Agent",
        "video_service_mode_label" => "Video Source Mode",
        "video_service_mode_generation" => "Generation",
        "video_service_mode_stock" => "Stock",
        "video_llm_service_none" => "No LLM",
        "tab_gallery" => "Gallery",
        "gallery_continue_btn" => "Continue Processing",
        "gallery_empty" => "No media files",
        "gallery_awaiting_label" => "⏳ Awaiting image review",
        "gallery_regen_same_tooltip" => "Regenerate with the same settings",
        "gallery_regen_custom_tooltip" => "Regenerate with custom settings",
        "gallery_regen_window_title" => "Regenerate",
        "gallery_regen_media_type_label" => "Media type",
        "gallery_regen_priority_image_label" => "Provider priority (image)",
        "gallery_regen_priority_video_label" => "Provider priority (video)",
        "gallery_regen_prompt_label" => "Prompt (empty = use saved prompt)",
        "gallery_regen_start_btn" => "Regenerate",
        "gallery_regen_loading" => "Generating...",
        "gallery_animate_all_btn" => "Animate all",
        "gallery_prompt_tooltip" => "View prompt",
        "gallery_prompt_window_title" => "Image prompt",
        "gallery_prompt_empty" => "Prompt not found",
        "gallery_prompt_copy_btn" => "Copy",
        "resume_depends_on_voice" => "(depends on voiceover)",
        "resume_dialog_title" => "Existing Files Found",
        "resume_dialog_folder" => "Folder:",
        "resume_resume_from" => "Resume from:",
        "resume_all_done" => "✓ All stages already completed",
        "resume_continue_btn" => "Continue",
        "resume_fresh_btn" => "Start Fresh",
        "resume_images" => "images",
        "resume_videos" => "videos",
        "resume_output_video" => "Final Video",
        "resume_timeline" => "Timeline",
        "resume_fill_missing_btn" => "Generate Missing",
        "task_history_title" => "Tasks",
        "task_history_empty" => "No tasks yet",
        "task_history_delete_tooltip" => "Remove from history",
        "task_history_stage_t" => "Tr",
        "task_history_stage_v" => "Vo",
        "task_history_stage_vid" => "Vid",
        "task_history_stage_s" => "Sub",
        "task_history_stage_m" => "Mon",
        "update_title" => "Update Available",
        "update_new_version" => "New version:",
        "update_changelog" => "Changelog:",
        "update_download_btn" => "Download",
        "update_later_btn" => "Later",
        _ => "",
    }
}
