/// Повертає переклад для російської мови.
pub fn translate_ru(key: &str) -> &'static str {
    match key {
        "app_title" => "Soloveyko.ai Video Maker",
        "tab_main" => "Основная",
        "tab_settings" => "Настройки",
        "pipeline_settings" => "Настройки пайплайна",
        "templates" => "Шаблоны",
        "storage" => "Путь сохранения",
        "api" => "API",
        "translation" => "Перевод",
        "voiceover" => "Озвучка",
        "video" => "Видеоряд",
        "editing" => "Монтаж",
        "editor_hint" => "Введите или вставьте сюда текст вашего будущего видеосценария...",
        "settings_general" => "Основные",
        "settings_general_title" => "Основные настройки",
        "settings_theme" => "Тема оформления",
        "settings_theme_desc" => "Выберите цветовую схему графического интерфейса:",
        "settings_theme_light" => "Светлая тема",
        "settings_theme_dark" => "Темная тема",
        "settings_theme_amoled" => "Черная AMOLED тема",
        "settings_accent" => "Цвет акцента",
        "settings_accent_desc" => "Выберите цвет выделений, активных элементов и навигации:",
        "settings_accent_quick" => "Быстрый выбор:",
        "settings_accent_custom" => "Собственный цвет из палитры:",
        "settings_data" => "Управление данными",
        "settings_data_desc" => "Открыть локальную папку с файлом настроек settings.json:",
        "settings_open_folder" => "Открыть папку пользователя",
        "settings_lang" => "Язык интерфейса",
        "settings_lang_desc" => "Выберите язык отображения программы:",
        "settings_lang_uk" => "Украинский",
        "settings_lang_en" => "Английский",
        "settings_lang_ru" => "Русский",
        "color_blue" => "Синий",
        "color_green" => "Зеленый",
        "color_red" => "Красный",
        "color_orange" => "Оранжевый",
        "color_purple" => "Фиолетовый",
        _ => "",
    }
}
