// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccentColor() {
  return window['go']['main']['App']['GetAccentColor']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function SetAccentColor(arg1) {
  return window['go']['main']['App']['SetAccentColor'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
