// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigPath():Promise<string>;

export function GetLanguage():Promise<string>;

export function OpenConfigDir():Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;
