// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {utils} from '../models';

export function GetAccentColor():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetOpenRouterAPIKey():Promise<string>;

export function GetOpenRouterAvailableModels():Promise<Array<api.OpenRouterModel>>;

export function GetOpenRouterCredits(arg1:string):Promise<number>;

export function GetOpenRouterSavedModels():Promise<Array<string>>;

export function GetSystemStats():Promise<utils.SystemStats>;

export function GetTheme():Promise<string>;

export function OpenConfigDir():Promise<void>;

export function SaveOpenRouterAPIKey(arg1:string):Promise<void>;

export function SaveOpenRouterModels(arg1:Array<string>):Promise<void>;

export function SetAccentColor(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
