// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccentColor() {
  return window['go']['main']['App']['GetAccentColor']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetOpenRouterAPIKey() {
  return window['go']['main']['App']['GetOpenRouterAPIKey']();
}

export function GetOpenRouterAvailableModels() {
  return window['go']['main']['App']['GetOpenRouterAvailableModels']();
}

export function GetOpenRouterCredits(arg1) {
  return window['go']['main']['App']['GetOpenRouterCredits'](arg1);
}

export function GetOpenRouterSavedModels() {
  return window['go']['main']['App']['GetOpenRouterSavedModels']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function SaveOpenRouterAPIKey(arg1) {
  return window['go']['main']['App']['SaveOpenRouterAPIKey'](arg1);
}

export function SaveOpenRouterModels(arg1) {
  return window['go']['main']['App']['SaveOpenRouterModels'](arg1);
}

export function SetAccentColor(arg1) {
  return window['go']['main']['App']['SetAccentColor'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
